force queue serialization
CHIP-SPV/H4I-MKLShim pull request #21
Opened 2024-05-06 11:00 UTC by pvelesko

2024-05-07 09:58 UTC, Sarbojit2019 requested changes
Please move the wait call inside macro 'ONEMKL_CATCH'. This will make sure any new API add will not miss it. Also it will help cover SOLVER.

For wait you can use 'status' which is nothing but the sycl event.
You can find the macro under "H4I-MKLShim/include/h4i/mklshim/mklshim.h"
Make below change

```
#define ONEMKL_CATCH(msg)     \
    status.wait_and_throw(); \
    __FORCE_MKL_FLUSH__(status); \
    __CATCH__(msg) 
```

2024-05-07 10:02 UTC, pvelesko commented
What about ONEMKL_CATCH_NO_FLUSH ? @Sarbojit2019

2024-05-07 10:08 UTC, Sarbojit2019 commented
Good point, ONEMKL_CATCH_NO_FLUSH special case I will take care of it.

2024-05-13 03:53 UTC, Sarbojit2019 approved these changes

2024-05-13 03:53 UTC, merged